Apparently, you shouldn't do super(FitsImage, self).__init__() if the parent class of FitsImage is a dataclass. In this case that will yield: TypeError: DataAccessor.__init__() missing 11 required positional arguments:....