Mypy is being overly cautious about inheritance
Mypy is being overly cautious about dataclass inheritance.
This only occurs for mypy type checking for Python 3.13, i.e. not for earlier Python versions - with their corresponding mypy versions.
One of the two error messages is
'
sourcefinder/accessors/lofarfitsimage.py:5: error: Definition of "__replace__"
Installing missing stub packages:
in base class "DataAccessor" is incompatible with definition in base class
"LofarAccessor"  [misc]
    class LofarFitsImage(FitsImage, LofarAccessor):
'
and the other one, for "class LofarCasaImage(CasaImage, LofarAccessor)", is similar.

No "__replace__" method has been implemented, so it is unclear where this error message comes from.

We therefore assume that mypy has inferred this incorrectly.